language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database teamwork;'
#  - psql -c "CREATE DATABASE testing_db;" -U postgres
#  - psql -c "CREATE USER postgres WITH PASSWORD 'bar';" -U postgres
env:
  global:
    - DB_USER=postgres
    - DB_HOST=localhost
    - DB_NAME=teamwork
    - DB_PASSWORD=''
    - SECRET=RANDOM_TOKEN_SECRET
